### ISSUE TITLE
cannot find random_walks.pkl

### ISSUE THREAD

**Issue by ForrestPi** [shenweichen/GraphEmbedding#1]
in deepwalk.py

 `
def train(self, embed_size=128, window_size=5, workers=3, iter=5, **kwargs):

        sentences = pd.read_pickle('random_walks.pkl')
        kwargs["sentences"] = sentences
        kwargs["min_count"] = kwargs.get("min_count", 0)
        kwargs["size"] = embed_size
        kwargs["sg"] = 1  # skip gram
        kwargs["hs"] = 1  # deepwalk use Hierarchical Softmax
        kwargs["workers"] = workers
        kwargs["window"] = window_size
        kwargs["iter"] = iter

`
cannot find random_walks.pkl

could you provide it ?
Thanks!

**Comment by shenweichen** [comment]
@ForrestPi  Hi, 
I'm sorry that I forget to update the codes in deepwalk.Now I have fixed this.
Please download the newest version of this repo~
