### ISSUE TITLE
执行deepwalk_wiki.py文件时的报错__init__() got an unexpected keyword argument 'size'

### ISSUE THREAD

**Issue by Dzhilin** [shenweichen/GraphEmbedding#50]
请问是怎么解决的呢？

**Comment by leekm189** [comment]
tf版本问题吧，试试tf1.4

**Comment by Dzhilin** [comment]
好的，我试试，谢谢！发自我的华为手机-------- 原始邮件 --------发件人： leekm189 ***@***.***>日期： 2021年4月29日周四 下午3:56收件人： shenweichen/GraphEmbedding ***@***.***>抄送： Dzhilin ***@***.***>, Author ***@***.***>主    题： Re: [shenweichen/GraphEmbedding] 执行deepwalk_wiki.py文件时的报错__init__() got an unexpected keyword argument 'size' (#50)

tf版本问题吧，试试tf1.4

**Comment by kexin997** [comment]
me too

**Comment by lostdirt** [comment]
hello,请问这个问题您解决了吗？

**Comment by bruceEeZhao** [comment]
这个问题是因为word2vec的版本问题，word2vec将size变成了vector_size，因此需要修改/models/deepwalk.py文件，
`
@@ -38,12 +38,12 @@ class DeepWalk:

         kwargs["sentences"] = self.sentences
         kwargs["min_count"] = kwargs.get("min_count", 0)
-        kwargs["size"] = embed_size
+        kwargs["vector_size"] = embed_size
         kwargs["sg"] = 1  # skip gram
         kwargs["hs"] = 1  # deepwalk use Hierarchical Softmax
         kwargs["workers"] = workers
         kwargs["window"] = window_size
-        kwargs["iter"] = iter
+        kwargs["epochs"] = iter
`

node2vec, struct2vec因为使用了word2vec也需要做同样的修改
